CREATE TABLE [dbo].[Show](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TvMazeShowId] [int] NOT NULL,
	[Name] [varchar](500) NULL,
 CONSTRAINT [PK_Show] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[Cast](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ShowId] [int] NULL,
	[TvMazePersonId] [int] NOT NULL,
	[Name] [varchar](100) NULL,
 CONSTRAINT [PK_Cast] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Cast]  WITH CHECK ADD  CONSTRAINT [FK_Cast_Show] FOREIGN KEY([ShowId])
REFERENCES [dbo].[Show] ([Id])
GO

ALTER TABLE [dbo].[Cast] CHECK CONSTRAINT [FK_Cast_Show]
GO

